name: Tagged Production Deploys for VS Code

on:
  workflow_dispatch:
  push:
    tags:
      - "mlogls-vscode-*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - run: "pnpm install"
      - run: "pnpm build:all"
      - run: |
          cd packages/mlogls-vscode
          echo "Don't forget to renew the Azure token every year"
          pnpm dlx vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.AZURE_PA_TOKEN }}
